### ISSUE TITLE
Ignoring internal qualifier?

### ISSUE THREAD

**Issue by dhomes** [eneko/SourceDocs#19]
## Brief Description
I'm trying to generate markdown from a framework project where only public types and methods are needed to be documented

## Steps to Reproduce

1. call sourcedocs generate on framework's xcproj root

### Expected Outcome
set of .md files for ONLY public classes and methods

### Actual Outcome
all types and methods marked as internal generate a .md
internal class Loader { 

   internal let ...
   internal func method1() {}
}

## Environment
- **Operating System:** Mojave 10.14.2
- **Xcode Version:** 10.0
- **SwiftDocs Version/SHA:** 0.5.1
- **Swift version:** 4.1

## Additional Comments

Looking for an option to strictly output public types and methods

**Comment by eneko** [comment]
Hi @dhomes, thank you for submitting this issue.  

Do you have any sample project to reproduce this issue? Or does it happen in all cases? 

Thanks,
Eneko

**Comment by minuscorp** [comment]
Fixed in #28 ?
