### ISSUE TITLE
Error: Failed to generate documentation

### ISSUE THREAD

**Issue by Mini-Stef** [eneko/SourceDocs#23]
## Brief Description

First try, can't produce the documentation.

Just install with brew.
cd to the XCode project, typed "sourcedocs generate", end up with

> Running xcodebuild
> Could not parse compiler arguments from `xcodebuild` output.
> Please confirm that `xcodebuild` is building a Swift module.
> Saved `xcodebuild` log file: /var/folders/9r/8wny4fv104z6hpdv5k8m5gsc0000gn/T/xcodebuild-A7DB1988-E214-4030-9D90-9C5A9AEC9A9E.log
> Error: Failed to generate documentation.
> 

The log file is miles long, but ends with 
> ** BUILD SUCCEEDED **

It is a swift framework with only one class

## Steps to Reproduce

See above

### Expected Outcome

I would expect the documentation to generate

### Actual Outcome

Nothing but the error message shown above

## Environment

- **Operating System:** macOS 10.14.6
- **Xcode Version:** 10.3
- **SwiftDocs Version/SHA:** ????
- **Swift version:** 5.1

**Comment by eneko** [comment]
Hi @Mini-Stef, thank you for your feedback.

Have you tried running `xcodebuild` from the command line without any arguments in your project? If that does not work, you might need to specify the Xcode project scheme and/or workspace. 

See [Usage Options](https://github.com/eneko/SourceDocs#usage-options) for more info.

**Comment by msalmonse** [comment]
I tried running xcodebuild (Xcode 11.0 Beta6, Catalina) and it complained about not having a provisioning profile ;^( Strange that I have no problems building with Xcode.

**Comment by minuscorp** [comment]
this should be fixed too in #28

**Comment by eneko** [comment]
@Mini-Stef Please try with the last SourceDocs 0.6.0 release
