### ISSUE TITLE
min acl doesn't seem to be working

### ISSUE THREAD

**Issue by adesentenac** [eneko/SourceDocs#31]
#25  Brief Description

--min-acl doesn't seem to be working, documentation for all types are generated, whatever their visibility.

## Steps to Reproduce

0. Have a Swift project with private, internal, public and open classes (cf. Test.zip)
1. Run: sourcedocs generate

### Expected Outcome

Only documentation for public and open classes is generated

### Actual Outcome

Documentation for all classes is generated

## Environment

- **Operating System:** macOS 10.15
- **Xcode Version:** 11.1
- **SwiftDocs Version/SHA:** 53cafb6fc4aeec422755de0ffdb1411b823aca18 (master)
- **Swift version:** 5.1

## Additional Comments

The result is the same when using --min-acl

## Demo Project

[Test.zip](https://github.com/eneko/SourceDocs/files/3796031/Test.zip)

**Comment by minuscorp** [comment]
Did you had the chance of debugging the command?

**Comment by eneko** [comment]
Hi @adesentenac, this is fixed now in `master`, will push a 0.6.1 release soon.

**Comment by eneko** [comment]
0.6.1 is now available on HomeBrew
