### ISSUE TITLE
Add support for JSDoc-style markup

### ISSUE THREAD

**Issue by captainbarbosa** [eneko/SourceDocs#37]
I wanted to flag a feature request here - it would be nice to have support for parsing [JSDoc-style](https://en.wikipedia.org/wiki/JSDoc) commenting. Such that this project could support doc generation from source code markup like this:

```swift
/**
 Returns a shiny new object.

 @param name The name of the object.
 @param options The options for the object.
 @return An initialized new shiny object.
 */
``` 

Where currently I can only markup source code like this:

```swift
/**
Returns a shiny new object.

- Parameters:
  - name: The name of the object.
  - options: The options for the object.
- Returns: An initialized new shiny object.
*/
```

Other than that I'm really satisfied with this library so far, thanks so much!

**Comment by eneko** [comment]
Hi @captainbarbosa! Thank you for your request. 

Unfortunately, neither Xcode nor Swift compiler support JSDoc documentation, which are used to build and extract documentation from the code.

Thank you,
Eneko
