### ISSUE TITLE
min-acl seems to be ignored on version 0.6.0. 

### ISSUE THREAD

**Issue by my-mo** [eneko/SourceDocs#38]
## Brief Description

`sourcedocs generate min-acl private` as an example just outputs everything regardless of access control. Maybe resolved in https://github.com/eneko/SourceDocs/pull/33 ?

Latest version of 0.6.1 doesn't seem to output anything other than a skeleton readme

## Steps to Reproduce

`sourcedocs generate min-acl private`

### Expected Outcome

Expected to only document private declarations.

### Actual Outcome

Documents everything.

## Environment

Xcode 10.3 or Xcode 11

**Comment by eneko** [comment]
Hi @my-mo, thank you for your feedback. This issue was fixed in 0.6.1

In regards of the "skeleton readme", this might be outlined in #30, which is currently being investigated and hopefully will be fixed in next release.
