### ISSUE TITLE
Create Swift Library in addition to executable

### ISSUE THREAD

**Issue by designatednerd** [eneko/SourceDocs#39]
This is an enhancement request - I'd like to take a stab at this if possible but wanted to make sure you're cool with this before I go too far down this road. 

I want to call SourceDocs directly from a Swift exectuable I'm making. Since SourceDocs already *is* an executable, I'd need to make a library as well. 

To make a library, I would need to: 

- Pull all the bits of SourceDocs into a library target except for `main` and make a bunch of stuff `public`
- Import the library in `main.swift`, and validate everything still runs the same.
- Create a way to pass in the options for `clean` and `generate` manually

Is this something you'd be amenable to?

**Comment by eneko** [comment]
Hi @designatednerd, that is a great idea. I've been wanting to do this for a while, because there is no unit test support for executables in SwiftPM, only for libraries. 

If you would like to give it a shot, please go for it. Otherwise, I might get to do it sometime in the near future.

Thanks!

**Comment by designatednerd** [comment]
I'll give it a shot! 🚀

**Comment by designatednerd** [comment]
Addressed by #42!
