### ISSUE TITLE
Package Dependency Graph does not render properly

### ISSUE THREAD

**Issue by acecilia** [eneko/SourceDocs#56]
I just discovered the `package` subcomand. This is SO COOL. Thanks!

## Brief Description

When generating the `Package Dependency Graph` I see two problems in the following image:

<img width="709" alt="Screen Shot 2020-05-29 at 10 26 02 PM" src="https://user-images.githubusercontent.com/7938671/83302817-433b1f00-a1fc-11ea-8088-ab9834c046aa.png">

1. If the version is not semantic versioning it says `unspecified`. I guess we could just change it to show the commit/branch...
2. This one I am not sure why is happening: the colors compared to [the sourcedocs docs](https://github.com/eneko/SourceDocs/blob/master/docs/Package.md) look wrong: the main package is not highlighted. Any idea why is that?

## Steps to Reproduce

Just run latest version on this project: https://github.com/acecilia/StackGen

## Environment

graphviz 2.44.0

**Comment by eneko** [comment]
Hi @acecilia , thanks for the feedback.

Both coloring and hiding the "unspecified" label are new updates for v1.2.0 (not yet released). If you look at the [docs for 1.1.0](https://github.com/eneko/SourceDocs/blob/1.1.0/docs/Package.md) you will see the graph looks very similar to yours.

At the moment, Swift Package Manager does not provide the commit sha of branch being used, when a version tag is not specified. It just says "unspecified" 😞

See the output of `swift package show-dependencies --format json`

If they implement that, I will add it to the graph, for sure 👍

**Comment by acecilia** [comment]
Awesome 😍 thanks!
