### ISSUE TITLE
Xcode 13 build issues

### ISSUE THREAD

**Issue by designatednerd** [eneko/SourceDocs#69]
Current version (1.2.1) of SourceDocs is not building on Xcode 13 as a standalone project or a dependency.

## Steps to Reproduce

1. Try to build SourceDocs with Xcode 13
1. Get a billion errors
1. Update Swift-Tools from 5.1 to 5.5 and fix associated warnings from the compiler (see https://github.com/designatednerd/SourceDocs/commit/392cf21f2cfb7cd2f4ff7c7189775f4a66cb2549), see at least some improvements
1. Attempt to update libraries to fix it, doesn't work (tried `swift-package-manager` 0.6, `SourceKitten` 0.31 + downgrading the `SwiftArgumentParser` version to match it, Leaving `SourceKitten` where it was and updating `SwiftArgumentParser` to 1.0.1)

## Environment

- **Operating System:** macOS 11.6
- **Xcode Version:** 13
- **SwiftDocs Version/SHA:** 1.2.1
- **Swift version:** 5.5

Note that I'm on an M1 mac and have not tried it on a non-M1, but if it's working for you that cold be a clue. 

## Additional Comments

There's some stuff on the SwiftPM repo that looks like it might fix this (basically, using `SwiftPMDataModel-auto` instead of `SwiftPM-auto` which doesn't have nearly as many dependencies), but it's not been released in a tagged version, and pointing to a specific commit would basically mean this can't be distributed as a library because commit-based releases can't be used in conjunction with tag based releases.

Banged my head on this for a couple hours, would appreciate any help!

**Comment by eneko** [comment]
Thank you @designatednerd, going to take a look

**Comment by eneko** [comment]
Should be resolved in #70

**Comment by calvincestari** [comment]
Big thank you for fixing this issue @eneko. I just pulled the latest update into apollo-ios and documentation is working perfectly with Xcode 13. 🎉
