### ISSUE TITLE
Can not install with homebrew

### ISSUE THREAD

**Issue by BinaryHammer** [eneko/SourceDocs#8]
## Brief Description
In your `README.md` you have a description how to install with Homebrew. It does not for me.

## Steps to Reproduce

1. Enter `$ brew install eneko/tap/sourcedocs`

### Expected Outcome

Installing sourcedocs without errors

### Actual Outcome

```
$ brew install eneko/tap/sourcedocs
==> Tapping eneko/tap
Cloning into '/usr/local/Homebrew/Library/Taps/eneko/homebrew-tap'...
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 4 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), done.
Tapped 1 formula (28 files, 21.3KB).
==> Installing sourcedocs from eneko/tap
sourcedocs: A full installation of Xcode.app is required to compile this software.
Installing just the Command Line Tools is not sufficient.
Xcode can be installed from the App Store.
Error: An unsatisfied requirement failed this build.
```

## Environment

- **Operating System:** macOS 10.13.4
- **SwiftDocs Version/SHA:** b5bff79481b576eca99f9621296b8f33f72e1e11
- **Swift version:** 4.1

## Additional Comments

Do I need Xcode installed? It is no prerequisite in the `README.md`.

## Demo Project

none

**Comment by eneko** [comment]
Hello @BinaryHammer, 

Installing with Homebrew requires building the sources for this project and its dependencies, and for that you will need Xcode installed on your machine.

I have uploaded a binary to the latest [0.5.0 release](
https://github.com/eneko/SourceDocs/releases/tag/0.5.0), please let me know if that works for you!

Thank you,
Eneko

**Comment by eneko** [comment]
@BinaryHammer could you please give this new install instructions a try? Installing the binary should remove the need for having Xcode installed in the machine.

https://github.com/eneko/SourceDocs/blob/master/README.md#download-binary

**Comment by BinaryHammer** [comment]
@eneko Yes it works with the download with curl and unzip. Thanks for this method.

_It may be easier to just add it to a release in GitHub for some._

**Comment by eneko** [comment]
Hello @BinaryHammer, happy to hear that the binary is working for you. We'll make sure all releases moving forward have a binary attachment.

There is also a new 0.5.1 release that should fix the Homebrew installation issue. Let me know if it works for you, if you would like to try it.
