### ISSUE TITLE
--skip-empty option in main and README but not in the latest release

### ISSUE THREAD

**Issue by jcabreram** [eneko/SourceDocs#80]
Even though the PR for the added feature with the option to skip elements with no comments (`--skip-empty`) has been merged since May 24th (#76), there hasn't been a release with that new feature.

The new option is even found in the README in the `main` branch but it's not usable as it's not included in the latest release.

**Comment by leszek-s** [comment]
@eneko Do you have any plans on when new version with this feature will be released? It would be useful to have a new release with a link to compiled binary for easier use.

**Comment by jcabreram** [comment]
@eneko have you given up with this project?

**Comment by eneko** [comment]
@jcabreram sorry for the delay. I haven't been much on GitHub lately. I'm looking for contributors to maintain SourceDocs, would you be interested? @leszek-s too
